# Generated by Django 4.1.7 on 2023-03-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comment',
        ),
    ]
